### ISSUE TITLE
systemd-based startup of xvfb/x11vnc fails

### ISSUE THREAD

**Issue by scotthasse** [joshbeard/puppet-display#3]
I am using your module in a Vagrant environment, but I get the following failures:

==> web: Error: Could not start Service[xvfb]: Execution of '/bin/systemctl start xvfb' returned 6: Failed to start xvfb.service: Unit xvfb.service failed to load: No such file or directory.
==> web: Wrapped exception:
==> web: Execution of '/bin/systemctl start xvfb' returned 6: Failed to start xvfb.service: Unit xvfb.service failed to load: No such file or directory.
==> web: Error: /Stage[main]/Display::Xvfb/Service[xvfb]/ensure: change from stopped to running failed: Could not start Service[xvfb]: Execution of '/bin/systemctl start xvfb' returned 6: Failed to start xvfb.service: Unit xvfb.service failed to load: No such file or directory.
==> web: Notice: /Stage[main]/Display::Xvfb/Service[xvfb]: Triggered 'refresh' from 1 events
==> web: Notice: /Stage[main]/Display::X11vnc/Package[x11vnc]: Dependency Service[xvfb] has failures: true
==> web: Warning: /Stage[main]/Display::X11vnc/Package[x11vnc]: Skipping because of failed dependencies
==> web: Notice: /Stage[main]/Display::X11vnc/File[x11vnc-init]: Dependency Service[xvfb] has failures: true
==> web: Warning: /Stage[main]/Display::X11vnc/File[x11vnc-init]: Skipping because of failed dependencies
==> web: Notice: /Stage[main]/Display::X11vnc/Service[x11vnc]: Dependency Service[xvfb] has failures: true
==> web: Warning: /Stage[main]/Display::X11vnc/Service[x11vnc]: Skipping because of failed dependencies

It seems to me that the system is attempting to ensure the services are running via systemd, but the module is not providing systemd-based init scripts.

Thanks,

Scott

**Comment by joshbeard** [comment]
Hi Scott,

Sorry about that - the module hasn't been updated for EL7 yet:  https://github.com/joshbeard/puppet-display/blob/master/metadata.json#L20

I'll work on getting this updated or accept any pull request adding it.

Thank you,
Josh

**Comment by awegmann** [comment]
Hi. I'm currently preparing/updating some machines and had this issue with CentOS 7.3. Are you interested in a pull request fixing the issue? Or are you working on this topic right now by yourself?

**Comment by joshbeard** [comment]
Definitely interested.  I haven't started on it yet.  It'd be great if you have something!

**Comment by awegmann** [comment]
Hi Josh. OK. I will add the missing "systemd reload" after creating the service start scripts. I will not change the service configuration to "native systemd". I think for this little services the compatibility mode of systemd is ok and it reduces complexity of the module. 
I'm not sure which other distributions also benefit from the fixes. As far as I know Debian 8 also switched to systemd as standard for init system. Ubuntu uses systemd sind 14.10 (I only read the documentation about that). Shall I do changes for this distributions as well? I can't test them immediately...
