### ISSUE TITLE
Cannot install module on ubuntu 16.04 LTS. with concat version 2.1.0

### ISSUE THREAD

**Issue by bissa** [joshbeard/puppet-display#4]
puppet module install joshbeard-display
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'joshbeard-display' (???)
  No version of 'joshbeard-display' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

puppetlabs/concat (>= 1.0.0 <2.0.0)

I assume this is because module does not support newer versions of concat then 2.0.0? and current version is 2.1.0

**Comment by joshbeard** [comment]
It should be fine, but the metadata is outdated.  I'll get that updated and a new version published

**Comment by joshbeard** [comment]
Fixed in 0.5.3
Forge:  https://forge.puppet.com/joshbeard/display/0.5.3/readme
Tag: https://github.com/joshbeard/puppet-display/tree/0.5.3
Commit: 6681b9872a0f023703377a912f3c7607af24dac7
