### ISSUE TITLE
Question about adding xclock capability

### ISSUE THREAD

**Issue by scotthasse** [joshbeard/puppet-display#5]
We use this module for starting a vnc server so that we can video record test runs.  During those runs it is helpful to have an xclock instance in the lower corner.  Is that something you view in scope for a plugin like this?  If so we could contribute the capability.  If not, feel free to resolve the issue.

Thanks,

Scott

**Comment by joshbeard** [comment]
Sorry for the late response.

This module is intended to get xvfb and x11vnc installed and configured.  From the sounds of it, I'd consider such a thing to be more appropriate for a "profile" class to implement (https://docs.puppet.com/pe/2016.4/r_n_p_intro.html).
